[General]
__userfile__=true
single_click_activate=true

[Palette]
base_color=#ff896c
highlight_color=#330099
highlighted_text_color=#ffffff
link_color=#0000ff
link_visited_color=#9b59b6
text_color=#000000
window_color=#aaaa7f
window_text_color=#000000

[Qt]
doubleClickInterval=400
style=Fusion
wheelScrollLines=3
